# Generated by Django 2.2.12 on 2022-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220123_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication_status',
            name='enabled',
        ),
        migrations.AddField(
            model_name='publication_topics',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
