apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: gic-group-6
data:
  script.sh: |-
    #!/bin/bash
    echo -e $POD_NAME
    if [[ "$POD_NAME" == "mongodb-0" ]]; then
      export MONGODB_REPLICA_SET_MODE="primary"
      export MONGODB_ROOT_USER=$MRU
      export MONGODB_ROOT_PASSWORD=$MRP
      export MONGODB_USER=$MU
      export MONGODB_PASSWORD=$MP
      export MONGODB_DATABASE="thenews"
    else
      export MONGODB_REPLICA_SET_MODE="secondary"
      export MONGODB_INITIAL_PRIMARY_PORT_NUMBER="27017"
      export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=$MRP
    fi
    echo -e $MONGODB_REPLICA_SET_MODE
    exec /opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: gic-group-6
spec:
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: mongodb
          image: bitnami/mongodb:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27017
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MRU
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root_username
            - name: MRP
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root_password
            - name: MU
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MP
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGODB_REPLICA_SET_NAME
              value: "replicaset"
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: "mongodb-0.mongodb.gic-group-6.svc.cluster.local"
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: "$(POD_NAME).mongodb.gic-group-6.svc.cluster.local"
            - name: MONGODB_REPLICA_SET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: replicate_key
          command:
            - /scripts/script.sh
          securityContext:
            runAsUser: 1001
          volumeMounts:
            - name: config
              mountPath: /scripts
            - name: mongodb-data
              mountPath: /bitnami/mongodb
      volumes:
        - name: config
          configMap:
            name: mongo-config
            defaultMode: 0755
            items:
              - key: script.sh
                path: script.sh
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              type: mongodb
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
        namespace: gic-group-6
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi